# Generated by Django 4.1.5 on 2023-03-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpresent',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
