# Generated by Django 4.1.5 on 2023-04-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_cart', '0002_productincart_delete_productcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('cart_ordered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='product_cart.cart')),
            ],
        ),
    ]
