# Generated by Django 4.1.5 on 2023-04-16 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_info', '0001_initial'),
        ('product_cart', '0002_productincart_delete_productcart'),
        ('order_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='client_info.userprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_ordered',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='product_cart.cart'),
        ),
    ]
